/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module address_check(clk, rst_n, virt_addr, end_cmd_in, addr_out, lookup_flg_out, end_cmd_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  output [13:0] addr_out;
  wire [13:0] base_addr;
  input clk;
  wire [12:0] cont;
  input end_cmd_in;
  output end_cmd_out;
  output lookup_flg_out;
  wire [12:0] p_blk;
  input rst_n;
  input [13:0] virt_addr;
  INVx1_ASAP7_75t_SRAM _21_ (
    .A(_16_),
    .Y(addr_out[9])
  );
  INVx1_ASAP7_75t_SRAM _22_ (
    .A(_01_),
    .Y(addr_out[10])
  );
  INVx1_ASAP7_75t_SRAM _23_ (
    .A(_02_),
    .Y(addr_out[11])
  );
  INVx1_ASAP7_75t_SRAM _24_ (
    .A(_03_),
    .Y(addr_out[12])
  );
  INVx1_ASAP7_75t_SRAM _25_ (
    .A(_04_),
    .Y(addr_out[13])
  );
  INVx1_ASAP7_75t_SRAM _26_ (
    .A(_05_),
    .Y(lookup_flg_out)
  );
  INVx1_ASAP7_75t_SRAM _27_ (
    .A(_06_),
    .Y(end_cmd_out)
  );
  INVx1_ASAP7_75t_SRAM _28_ (
    .A(_07_),
    .Y(addr_out[0])
  );
  INVx1_ASAP7_75t_SRAM _29_ (
    .A(_08_),
    .Y(addr_out[1])
  );
  INVx1_ASAP7_75t_SRAM _30_ (
    .A(_09_),
    .Y(addr_out[2])
  );
  INVx1_ASAP7_75t_SRAM _31_ (
    .A(_10_),
    .Y(addr_out[3])
  );
  INVx1_ASAP7_75t_SRAM _32_ (
    .A(_11_),
    .Y(addr_out[4])
  );
  INVx1_ASAP7_75t_SRAM _33_ (
    .A(_12_),
    .Y(addr_out[5])
  );
  INVx1_ASAP7_75t_SRAM _34_ (
    .A(_13_),
    .Y(addr_out[6])
  );
  INVx1_ASAP7_75t_SRAM _35_ (
    .A(_14_),
    .Y(addr_out[7])
  );
  INVx1_ASAP7_75t_SRAM _36_ (
    .A(_15_),
    .Y(addr_out[8])
  );
  NOR2xp33_ASAP7_75t_SRAM _37_ (
    .A(virt_addr[0]),
    .B(virt_addr[1]),
    .Y(_17_)
  );
  NOR4xp25_ASAP7_75t_SRAM _38_ (
    .A(virt_addr[2]),
    .B(virt_addr[3]),
    .C(virt_addr[4]),
    .D(virt_addr[5]),
    .Y(_18_)
  );
  OR4x1_ASAP7_75t_SRAM _39_ (
    .A(virt_addr[10]),
    .B(virt_addr[11]),
    .C(virt_addr[12]),
    .D(virt_addr[13]),
    .Y(_19_)
  );
  NOR5xp2_ASAP7_75t_SRAM _40_ (
    .A(virt_addr[6]),
    .B(virt_addr[7]),
    .C(virt_addr[8]),
    .D(virt_addr[9]),
    .E(_19_),
    .Y(_20_)
  );
  NAND3xp33_ASAP7_75t_SRAM _41_ (
    .A(_17_),
    .B(_18_),
    .C(_20_),
    .Y(_00_)
  );
  DFFASRHQNx1_ASAP7_75t_SRAM _42_ (
    .CLK(clk),
    .D(virt_addr[10]),
    .QN(_01_),
    .RESETN(1'h1),
    .SETN(rst_n)
  );
  DFFASRHQNx1_ASAP7_75t_SRAM _43_ (
    .CLK(clk),
    .D(virt_addr[11]),
    .QN(_02_),
    .RESETN(1'h1),
    .SETN(rst_n)
  );
  DFFASRHQNx1_ASAP7_75t_SRAM _44_ (
    .CLK(clk),
    .D(virt_addr[12]),
    .QN(_03_),
    .RESETN(1'h1),
    .SETN(rst_n)
  );
  DFFASRHQNx1_ASAP7_75t_SRAM _45_ (
    .CLK(clk),
    .D(virt_addr[13]),
    .QN(_04_),
    .RESETN(1'h1),
    .SETN(rst_n)
  );
  DFFASRHQNx1_ASAP7_75t_SRAM _46_ (
    .CLK(clk),
    .D(_00_),
    .QN(_05_),
    .RESETN(1'h1),
    .SETN(rst_n)
  );
  DFFASRHQNx1_ASAP7_75t_SRAM _47_ (
    .CLK(clk),
    .D(end_cmd_in),
    .QN(_06_),
    .RESETN(1'h1),
    .SETN(rst_n)
  );
  DFFASRHQNx1_ASAP7_75t_SRAM _48_ (
    .CLK(clk),
    .D(virt_addr[0]),
    .QN(_07_),
    .RESETN(1'h1),
    .SETN(rst_n)
  );
  DFFASRHQNx1_ASAP7_75t_SRAM _49_ (
    .CLK(clk),
    .D(virt_addr[1]),
    .QN(_08_),
    .RESETN(1'h1),
    .SETN(rst_n)
  );
  DFFASRHQNx1_ASAP7_75t_SRAM _50_ (
    .CLK(clk),
    .D(virt_addr[2]),
    .QN(_09_),
    .RESETN(1'h1),
    .SETN(rst_n)
  );
  DFFASRHQNx1_ASAP7_75t_SRAM _51_ (
    .CLK(clk),
    .D(virt_addr[3]),
    .QN(_10_),
    .RESETN(1'h1),
    .SETN(rst_n)
  );
  DFFASRHQNx1_ASAP7_75t_SRAM _52_ (
    .CLK(clk),
    .D(virt_addr[4]),
    .QN(_11_),
    .RESETN(1'h1),
    .SETN(rst_n)
  );
  DFFASRHQNx1_ASAP7_75t_SRAM _53_ (
    .CLK(clk),
    .D(virt_addr[5]),
    .QN(_12_),
    .RESETN(1'h1),
    .SETN(rst_n)
  );
  DFFASRHQNx1_ASAP7_75t_SRAM _54_ (
    .CLK(clk),
    .D(virt_addr[6]),
    .QN(_13_),
    .RESETN(1'h1),
    .SETN(rst_n)
  );
  DFFASRHQNx1_ASAP7_75t_SRAM _55_ (
    .CLK(clk),
    .D(virt_addr[7]),
    .QN(_14_),
    .RESETN(1'h1),
    .SETN(rst_n)
  );
  DFFASRHQNx1_ASAP7_75t_SRAM _56_ (
    .CLK(clk),
    .D(virt_addr[8]),
    .QN(_15_),
    .RESETN(1'h1),
    .SETN(rst_n)
  );
  DFFASRHQNx1_ASAP7_75t_SRAM _57_ (
    .CLK(clk),
    .D(virt_addr[9]),
    .QN(_16_),
    .RESETN(1'h1),
    .SETN(rst_n)
  );
  assign base_addr = 14'h0000;
  assign cont = 13'h0000;
  assign p_blk = 13'h0000;
endmodule
